CREATE DATABASE SUNVIEW;
USE SUNVIEW;
CREATE TABLE INFO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR (100) NOT NULL,
    DOB DATE NULL,
    PHONE VARCHAR (50) NOT NULL,
    TITLE VARCHAR (50) NOT NULL,
    EMAIL VARCHAR(100)NOT NULL,
    SEX VARCHAR(50) NULL,
    ADDRESS VARCHAR(50)
    );
CREATE TABLE AUTHORIZATION (
	ID INT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);
CREATE TABLE DOW (
	ID INT PRIMARY KEY,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    DAY DATE NOT NULL,
    ID_INFO INT 
);
CREATE TABLE PRODUCT (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    UNIT_PRICE FLOAT NOT NULL
);
CREATE TABLE CONDITIONS (
	ID INT PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    PERCENT FLOAT NOT NULL
);
CREATE TABLE ROOM (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_INFO INT NULL,
    SLOTS INT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CHECK_IN TIME NULL,
    CHECK_OUT TIME NULL,
    DAY_CHECKIN DATE NULL,
    DAY_CHECKOUT DATE NULL,
    SERVICE VARCHAR(50) NULL
);
CREATE TABLE ACTIVITY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_PRODUCT INT NOT NULL,
    QUANTITY INT NOT NULL,
    DAY DATE NOT NULL,
    TOTAL_PRICE FLOAT NOT NULL
);
CREATE TABLE BILL (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ACT INT NOT NULL,
    ID_CONT INT NULL,
    ID_INFO INT NOT NULL
);
CREATE TABLE SALARY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_INFO INT,
    HOUR_RATE FLOAT NOT NULL,
    HOUR_WORK FLOAT NOT NULL,
    TOTAL FLOAT NOT NULL,
    DAY DATE NOT NULL
);
CREATE TABLE STORAGE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_PRODUCT INT,
    NAME VARCHAR(50) NOT NULL,
    QUANTITY INT NOT NULL,
    IMPORT DATE NULL,
    EXPORT DATE 
    ); 
ALTER TABLE AUTHORIZATION ADD INDEX idx_email (EMAIL);
ALTER TABLE INFO ADD INDEX idx_email (EMAIL);
ALTER TABLE DOW MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE INFO MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE PRODUCT MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE CONDITIONS MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE ROOM MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE ACTIVITY MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE BILL MODIFY ID INT AUTO_INCREMENT;
ALTER TABLE STORAGE MODIFY EXPORT DATE NULL ;
ALTER TABLE AUTHORIZATION ADD CONSTRAINT FK_AUTHORIZATTION_INFO FOREIGN KEY (ID) REFERENCES INFO (ID);
ALTER TABLE DOW ADD CONSTRAINT FK_DOW_INFO FOREIGN KEY (ID_INFO) REFERENCES INFO (ID);
ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_INFO FOREIGN KEY (ID_INFO) REFERENCES INFO (ID);
ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID);
ALTER TABLE BILL ADD CONSTRAINT FK_BILL_ACTIVITY FOREIGN KEY (ID_ACT) REFERENCES ACTIVITY (ID);
ALTER TABLE BILL ADD CONSTRAINT FK_BILL_CONDITION FOREIGN KEY (ID_CONT) REFERENCES CONDITIONS (ID);
ALTER TABLE BILL ADD CONSTRAINT FK_BILL_INFO FOREIGN KEY (ID_INFO) REFERENCES INFO (ID);
ALTER TABLE SALARY ADD CONSTRAINT FK_SALARY_INFO FOREIGN KEY (ID_INFO) REFERENCES INFO (ID);
ALTER TABLE STORAGE ADD CONSTRAINT FK_STORAGE_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID);
ALTER TABLE AUTHORIZATION ADD CONSTRAINT FK_AUTHORIZATION_INFO FOREIGN KEY (EMAIL) REFERENCES INFO (EMAIL);
